#!/usr/bin/env python

import logging
import socket
import subprocess
import sys
import time

import Adafruit_CharLCD as LCD

def ip_address():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("gmail.com", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception as e:
        logging.error("Exception({0}): {1}".format(e.errno, e.strerror))
        return None

def wifi_ssid():
    wifi_info = subprocess.check_output(["wpa_cli", "status"])
    for line in wifi_info.split("\n"):
        if line.startswith("ssid"):
            ssid = line.split("=")[1]
            return ssid
    return None

def main():
    logging.basicConfig(
        filename='/var/log/lcd-panel.log',
        format='%(asctime)s [%(levelname)s] (%(module)s:%(lineno)d) %(message)s',
        level=logging.INFO
    )
    if sys.stdout.isatty():
        logging.getLogger().addHandler(logging.StreamHandler())

    lcd = LCD.Adafruit_CharLCDPlate()

    lcd.create_char(1, [2, 9, 5, 21, 5, 9, 2, 0]) # Wifi icon!

    logging.info('Turning on backlight')
    lcd.set_backlight(1)
    lcd.message("Looking for Wifi...")

    ssid = wifi_ssid()
    ip = ip_address()
    while ssid is None or ip is None:
        logging.info("Waiting for WiFi, sleeping")
        time.sleep(1)
        ssid = wifi_ssid()
        ip = ip_address()

    lcd.clear()
    lcd.message('\x01 ' + ssid + "\n" + ip)
    logging.info("Found Wifi (SSID: %s, IP: %s)", ssid, ip)

    # Turn backlight off after a few seconds
    time.sleep(5)
    logging.info('Turning off backlight')
    lcd.set_backlight(0)

if __name__ == '__main__':
    main()
