#!/usr/bin/env python

import logging

import Adafruit_CharLCD as LCD

logging.basicConfig(
    filename='/var/log/lcd-panel.log',
    format='%(asctime)s [%(levelname)s] (%(module)s:%(lineno)d) %(message)s',
    level=logging.INFO
)

def main():
    lcd = LCD.Adafruit_CharLCDPlate()

    # Turn off backlight
    lcd.set_color(0.0, 0.0, 0.0)
    logging.info('Turning off backlight')

    # Clear text
    lcd.clear()
    logging.info('Clearing text')

if __name__ == '__main__':
    main()
