#!/bin/sh
### BEGIN INIT INFO
# Provides:          lcd-panel
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Do stuff with the LCD panel at startup
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Showing wifi details on LCD panel"

    /opt/lcd/lcd-show-wifi-details &

    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Clearing LCD panel and turning off backlight"

    /opt/lcd/lcd-clear-panel

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/$(basename $0) {start|stop}"
    exit 1
    ;;
esac
